services:
  wolf:
    image: ghcr.io/games-on-whales/wolf:stable
    container_name: wolf
    restart: unless-stopped
    network_mode: host
    privileged: false
    
    # Bind mounts
    volumes:
      - /etc/wolf/:/etc/wolf:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /dev/:/dev/:rw
      - /run/udev:/run/udev:rw
      - ${WOLF_BASE_DIR:-.}/profiles:/etc/wolf/profile_data:rw
      - ${WOLF_BASE_DIR:-.}/state:/var/lib/wolf:rw
    
    # GPU e dispositivos
    devices:
      - /dev/dri
      - /dev/uinput
      - /dev/uhid
    
    device_cgroup_rules:
      - 'c 13:* rmw'
    
    # Environment
    environment:
      - RUST_LOG=${RUST_LOG:-info}
      - WOLF_LOG_LEVEL=${WOLF_LOG_LEVEL:-debug}
      - WOLF_DATA_DIR=/var/lib/wolf
      - WOLF_CONFIG_DIR=/etc/wolf/cfg
      - RUST_BACKTRACE=1
      - WOLF_RENDER_NODE=${WOLF_RENDER_NODE:-/dev/dri/renderD128}
      - GAMESCOPE_WIDTH=${GAMESCOPE_WIDTH:-1920}
      - GAMESCOPE_HEIGHT=${GAMESCOPE_HEIGHT:-1080}
